uploads = []
outputs = []

[[generated]]
id = "AY8iXbGJnDslEhyPCzu9o"
uri = "file://public/img/strip-books-1.png"
type = "image"
title = "stack of vintage books"

[[generated]]
id = "7YXAN7qjDQX9U93Pwk9zL"
uri = "file://public/img/strip-books-2.png"
type = "image"
title = "cozy reading scene"

[[generated]]
id = "eRCHGCskB8ZvrP6g6hQsW"
uri = "file://public/img/strip-books-3.png"
type = "image"
title = "modern bookstore shelves"

[[generated]]
id = "VxXEmKHBYaHc2fVtxI_d0"
uri = "file://public/img/strip-books-4.png"
type = "image"
title = "open book pages"

[[generated]]
id = "lSm5c5Q-55JiNVjLA1xj3"
uri = "file://public/img/strip-books-5.png"
type = "image"
title = "person reading library"

[[generated]]
id = "dSEElAURbDrSp4zxYJKU8"
uri = "file://public/img/fashion-books-1.png"
type = "image"
title = "art books collection"

[[generated]]
id = "yptWmU_rXb-FqnvYmDXvC"
uri = "file://public/img/fashion-books-2.png"
type = "image"
title = "reader with book and coffee"
